version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: java7-glassfish4
    ports:
      - 4848:4848
      - 8080:8080
      - 8181:8181
#    volumes:
#      - ./target/dockerized.war:/opt/glassfish/webapps/dockerized.war
